"""Render the bilingual static landing. Store URLs must be verified before adding."""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
stores=json.loads((ROOT/'stores.json').read_text())
copy={
'ro': dict(nav=['Cum funcționează','Datele tale','Întrebări'],download='Descarcă aplicația',eyebrow='MAI PUȚINE HÂRTII. MAI MULTĂ ORDINE.',title='Bonul scanat.<br>Factura solicitată.',intro='Scanează bonul de combustibil, alege firma și solicită factura. Documentele tale rămân la îndemână, pe telefon.',soon='În curând',note='Pregătim lansarea pentru iPhone și Android.',stepsTitle='De la bon la solicitare,<br>în câțiva pași.',stepsIntro='Datele importante, într-un singur loc. Tu verifici și confirmi fiecare solicitare.',steps=[('Scanează bonul','Citește codul QR cu camera sau introdu datele manual. Aplicația verifică bonul la furnizor.'),('Alege firma','Adaugă firma prin CUI și verifică datele de facturare înainte de trimitere.'),('Păstrează documentele','Consultă istoricul, descarcă documentul disponibil și distribuie-l când ai nevoie.')],privacyTitle='Pe telefonul tău.<br>Sub controlul tău.',privacyIntro='Fără cont de creat. Fără istoricul bonurilor pe un server propriu al aplicației.',privacy=[('Acces offline','Istoricul și documentele deja descărcate sunt disponibile și fără internet.'),('Tu confirmi','Verifici datele înainte de trimitere. Emiterea nu se repetă automat după o întrerupere.'),('Ștergere locală','Administrezi firmele, bonurile și documentele direct din aplicație.')],faqTitle='Bine de știut.',faq=[('Cu ce bonuri funcționează?','Aplicația se conectează la serviciile de facturare OMV și Petrom din România. Eligibilitatea bonurilor și termenele de facturare sunt stabilite de furnizor.'),('Am nevoie de internet?','Da, pentru verificarea bonului, căutarea firmei, trimiterea solicitării și descărcarea documentelor. Istoricul și fișierele descărcate sunt accesibile offline.'),('Documentul descărcat este factura finală?','Documentul disponibil în portal poate fi o solicitare de facturare. Verifică statutul facturii la furnizor și, când este aplicabil, în SPV.'),('Trebuie să îmi creez un cont?','Nu. Datele firmelor, istoricul și documentele sunt păstrate local. Aplicația contactează furnizorii pentru facturare și Expo pentru actualizări tehnice.')],legal=['Confidențialitate','Termeni și condiții','Suport','Ștergerea datelor'],disclaimer='Aplicație independentă, neafiliată, nesponsorizată și neaprobată de OMV sau Petrom.',caption='Previzualizare ilustrativă · date demonstrative',phone=['Bon verificat','Firmă','Firma ta SRL','Date de facturare verificate de tine','Generează factura','Bon','Istoric','Firme','Despre'],small=['Fără cont','Date păstrate local','iOS și Android'],policy='Vezi politica de confidențialitate',switch='English'),
'en': dict(nav=['How it works','Your data','Questions'],download='Get the app',eyebrow='LESS PAPER. MORE ORDER.',title='Scan a receipt.<br>Request an invoice.',intro='Scan your fuel receipt, select your company and request an invoice. Keep your documents close, on your phone.',soon='Coming soon',note='We’re preparing the launch for iPhone and Android.',stepsTitle='From receipt to request,<br>one step at a time.',stepsIntro='The details you need, in one place. You review and confirm every request.',steps=[('Scan your receipt','Read the QR code with your camera or enter the details manually. The app checks the receipt with the provider.'),('Select your company','Look up your company by its Romanian tax ID and review billing details before submitting.'),('Keep your documents','Check your history, download the available document and share it when needed.')],privacyTitle='On your phone.<br>Under your control.',privacyIntro='No account to create. No receipt history stored on an app-operated server.',privacy=[('Available offline','Your history and previously downloaded documents are available without an internet connection.'),('You confirm','Review the details before submitting. Issuance is not automatically retried after an interruption.'),('Local deletion','Manage companies, receipts and documents directly in the app.')],faqTitle='Good to know.',faq=[('Which receipts are supported?','The app connects to OMV and Petrom invoicing services in Romania. Receipt eligibility and invoicing deadlines are determined by the provider.'),('Do I need an internet connection?','Yes, to verify receipts, look up companies, submit requests and download documents. Your history and downloaded files are available offline.'),('Is the downloaded document the final invoice?','A portal document may be an invoice request. Check the invoice status with the provider and, where applicable, in SPV.'),('Do I need an account?','No. Company details, history and documents are stored locally. The app contacts invoicing providers and Expo for technical updates.')],legal=['Privacy','Terms and conditions','Support','Data deletion'],disclaimer='An independent app, not affiliated with, sponsored or endorsed by OMV or Petrom.',caption='Illustrative preview · sample data',phone=['Bon verificat','Firmă','Firma ta SRL','Date de facturare verificate de tine','Generează factura','Bon','Istoric','Firme','Despre'],small=['No account','Locally stored data','iOS and Android'],policy='Read the privacy policy',switch='Română')}

def render(lang,root=False):
 c=copy[lang]; prefix='' if root else '../'; legal='ro/' if root else ''; other='en/index.html' if root else ('../en/index.html' if lang=='ro' else '../ro/index.html')
 def buttons():
  out=''
  for key,label in [('ios','App Store'),('android','Google Play')]:
   url=stores.get(key)
   if url and not url.startswith(('https://apps.apple.com/','https://testflight.apple.com/','https://play.google.com/')):raise ValueError('Unsupported store URL')
   content=f'<span class="store-os">{ "iOS" if key=="ios" else "ANDROID" }</span><span><small>{c["download"] if url else c["soon"]}</small><strong>{label}</strong></span>'
   out+=f'<a class="store" href="{escape(url)}">{content}</a>' if url else f'<button class="store" type="button" disabled aria-label="{label}: {c["soon"]}">{content}</button>'
  return out
 steps=''.join(f'<li><span class="step-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></li>' for i,(title,text) in enumerate(c['steps']))
 features=''.join(f'<div><h3>{title}</h3><p>{text}</p></div>' for title,text in c['privacy'])
 faqs=''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in c['faq'])
 links=''.join(f'<a href="{legal}{key}.html">{label}</a>' for key,label in zip(['privacy','terms','support','deletion'],c['legal']))
 p=c['phone']
 return f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Combustibil · {"Bonuri și facturi, pe telefon" if lang=='ro' else "Fuel receipts, organised"}</title><meta name="description" content="{c['intro']}"><meta name="color-scheme" content="light"><link rel="icon" type="image/svg+xml" href="{prefix}logo.svg"><link rel="stylesheet" href="{prefix}home.css"><link rel="alternate" hreflang="{'en' if lang=='ro' else 'ro'}" href="{other}"></head>
<body><a class="skip" href="#main">{'Sari la conținut' if lang=='ro' else 'Skip to content'}</a>
<header class="wrap"><a class="brand" href="index.html"><img src="{prefix}logo.svg" alt="" width="34" height="34">Combustibil</a><nav aria-label="{'Navigare' if lang=='ro' else 'Navigation'}"><a href="#how">{c['nav'][0]}</a><a href="#privacy">{c['nav'][1]}</a><a href="#faq">{c['nav'][2]}</a></nav><a class="language" href="{other}" lang="{'en' if lang=='ro' else 'ro'}">{c['switch']}</a><a class="nav-cta" href="#download">{c['download']}</a></header>
<main id="main"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow">{c['eyebrow']}</p><h1>{c['title']}</h1><p class="lead">{c['intro']}</p><div class="stores" id="download">{buttons()}</div><p class="availability">{c['note'] if not all(stores.values()) else ''}</p><ul class="benefits">{''.join(f'<li>{x}</li>' for x in c['small'])}</ul></div>
<figure class="showcase"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><div class="phone"><div class="island"></div><div class="status"><span>9:41</span><span>▮▮▮ ▰</span></div><div class="phone-content"><img class="app-logo" src="{prefix}logo.svg" width="44" height="44" alt=""><div class="receipt-status">{p[0]}</div><div class="amount">154,94 <span>lei</span></div><p class="receipt-info">13.09.2026 · OMV</p><div class="receipt-rule"></div><span class="field-label">{p[1]}</span><strong class="company">{p[2]}</strong><p class="company-note">{p[3]}</p><div class="fake-button">{p[4]}</div><div class="document"><span>PDF</span><div><strong>Documente, la îndemână</strong><small>Salvate pe telefonul tău</small></div></div></div><div class="phone-tabs"><span class="active">⌗<small>{p[5]}</small></span><span>▤<small>{p[6]}</small></span><span>▥<small>{p[7]}</small></span><span>ⓘ<small>{p[8]}</small></span></div><div class="home-indicator"></div></div><figcaption>{c['caption']}</figcaption></figure></section>
<section class="how wrap" id="how"><div><p class="eyebrow">{'SIMPLU, DE LA ÎNCEPUT' if lang=='ro' else 'SIMPLE FROM THE START'}</p><h2>{c['stepsTitle']}</h2><p class="section-intro">{c['stepsIntro']}</p></div><ol class="steps">{steps}</ol></section>
<section class="privacy" id="privacy"><div class="wrap privacy-grid"><div><img src="{prefix}logo.svg" width="66" height="66" alt=""><h2>{c['privacyTitle']}</h2><p class="section-intro">{c['privacyIntro']}</p><a class="text-link" href="{legal}privacy.html">{c['policy']} <span aria-hidden="true">↗</span></a></div><div class="privacy-features">{features}</div></div></section>
<section class="faq wrap" id="faq"><div><p class="eyebrow">FAQ</p><h2>{c['faqTitle']}</h2><a class="text-link" href="{legal}support.html">{'Ai nevoie de ajutor?' if lang=='ro' else 'Need a hand?'} ↗</a></div><div>{faqs}</div></section></main>
<footer class="wrap"><div class="footer-top"><a class="brand" href="index.html"><img src="{prefix}logo.svg" alt="" width="28" height="28">Combustibil</a><div class="legal-links">{links}</div></div><div class="footer-bottom"><p>© 2026 <a href="https://hetmann.tech">HETMANN TECHNOLOGIES SRL</a></p><p>{c['disclaimer']}</p></div></footer></body></html>'''
(ROOT/'index.html').write_text(render('ro',True))
for lang in copy:(ROOT/lang/'index.html').write_text(render(lang))
